### ISSUE TITLE
Space after colon breaks parser

### ISSUE THREAD

**Issue by mskelton** [tree-sitter/tree-sitter-css#43]
The recent changes to the scanner with handling of colons for pseudo classes I believe broke parsing in certain circumstances including this example in the atom.io.css example file.

```css
@media screen and (min-width: 0 0) {
    .tooltipped-multiline: after {
    width: 250px;
}
}.tooltipped-sticky:before, .tooltipped-sticky:after {

```

<img width="914" alt="image" src="https://github.com/tree-sitter/tree-sitter-css/assets/25914066/007930d9-12e0-44c5-9d9a-557de2b13b2e">
