### ISSUE TITLE
feature: Support escape charater

### ISSUE THREAD

**Issue by Huliiiiii** [tree-sitter/tree-sitter-css#54]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

The current Tree-sitter CSS grammar does not handle escaped characters in CSS strings, selectors, or identifiers as expected.

### Describe the solution you'd like

```css
      ↓ /* Escape charater for class name */
.hover\:bg-blue-600::before {
  content: "\f123"; /* Unicode character escaped */
}
```

Tree-sitter CSS grammar should support parsing of escaped characters in all valid CSS contexts, including but not limited to: 
- String literals 
- Selectors 

### Describe alternatives you've considered

n/a
