### ISSUE TITLE
Attribute arguments scoped as plain_value

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-css#6]
```css
p[data-foo]::before {
  content: attr(data-foo);
}
```

The argument passed to `attr()` should be `attribute_name` instead of `plain_value`.

[Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/attr).
