### ISSUE TITLE
Transitioned properties scoped as plain_value

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-css#7]
```css
div {
  transition: width 2s ease;
  transition-property: opacity;
}
```

Transitioned properties (`width`, `opacity`, etc.) should be `property_name` instead of `plain_value`.

[Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions).
