### ISSUE TITLE
Negative numbers scoped as plain_value

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-css#8]
```css
body {
  top: 3px;
  left: -2px;
}
```

Negative numbers should be `integer_value` or `float_value` instead of `plain_value`.
