### ISSUE TITLE
Pseudo-class arguments scoped as tag_name

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-css#9]
```css
span:nth-child(even),
tr:nth-child(2n+1),
div:nth-child(4) {}
```

Arguments for pseudo-classes should have appropriate scopes.

[Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child).
